### ISSUE TITLE
Logout icon doesn't renders well on kali linux

### ISSUE THREAD

**Issue by chrispetrou** [CosasDePuma/NameNotFound#3]
I know this is just a minor bug but I thought it would be good to let you know:

![0](https://user-images.githubusercontent.com/36112975/66272105-2d907800-e86e-11e9-8e36-f62fac0b8915.png)

As you can see from the above picture the logout icon doesn't render on kali linux and Mozilla Firefox 52.9.0.

**Comment by CosasDePuma** [comment]
I have just tested the shell on the last Kali Linux version. 
It works fine. I will let the issue open until I tested it in Firefox 52.9

![icon](https://user-images.githubusercontent.com/26680023/66476258-6bbbb080-ea95-11e9-92be-f27cd07d4fa6.JPG)

`Tested on Mozilla Firefox Quantum 60`
