### ISSUE TITLE
Contradiction between displayed user and real user

### ISSUE THREAD

**Issue by chrispetrou** [CosasDePuma/NameNotFound#4]
From the source code I see that user displayed in the right upper corner is the result of `@get_current_user()`, which per the PHP documentation is the name of the owner of the current PHP script and not the user executing it. I don't know if this is intended script behavior but it's a bit weird the `whoami` command to display a different user than the one displayed in the upper corner. 

As I said I didn't know if it's intended but if it's not, then an easy fix to that issue would be to modify the code to:
```php
function GatherInformation()
{
    $user = shell_exec('whoami');
    $info = array(
        'USER' => "$user",
```

**Comment by CosasDePuma** [comment]
Some ideas to fix this bug without using shell/exec because shell/exec functions are used by regex-based anti-webshell programs.

[Here](https://stackoverflow.com/questions/7771586/how-to-check-what-user-php-is-running-as) is a good solution:

```php
file_put_contents(".x", ""); // Create a new file
$user = fileowner(".x");     // Check the file owner
unlink(".x");                // Remove the file
```

**Comment by chrispetrou** [comment]
Yes, that a good solution too, but what's the point of trying to avoid `shell_exec` if it's already being used in `RunCommand()` function? Also the other disadvantage of the above solution is that you are actually creating a file which means that you touch the disk - that is something that modern AVs also pay special attention to.

**Comment by CosasDePuma** [comment]
Yeah, my intention is to avoid use `shell_exec` in `RunCommand( )`. I am trying to find an alternative.
The disadvantage of the above solution is also more code, that equals more file size, and I want to refractor and minimize the webshell.

I am going to investigate a bit more and, if I don't find anything, I will use your first solution to this bug.
